### PR TITLE
HabitTracker.svelte Component

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
Hello everyone! I've wanted to change a few things and submit a PR and saw that there was a link to a guide on using Svelte for Obsidian plugins and well... I'm in love Svelte, and I had to port the whole thing. I've also added a few features from the TODO and as I've said I also wanted to change a few things.

- chore: UI was rewritten as a Svelte component
	- thanks to svelte, the ui component now only ~~60%~~ as big, even with all the features below added 🎉
		- I just realized my original calculation was not accurate, since I forgot to include the CSS. The component is only 53% of the characters as the files it replaces (6946 chars v 12999 chars)
	- the CSS is different, because I chose to rewrite it inside the component itself without any verbose css naming conventions (svelte styles are scoped by default). ofc we can adjust the design before merging.
	- I also chose to include date-fns, because it looked like the API would fit the previous date handling well
- feat: show current day as green and add the option to mark an additional day (e.g. the current journal files day)
	- we can talk about the colors here, and if we event want to make them configurable maybe?
- feat: add button that allows to add a new habit file
	- i'm not sure on the design on this one, so I made it configurable. either way a button get's displayed for the empty state so the onboarding is dead simple.
- feat: check for habit updates every 5 seconds (great for obsidian sync)
	- i thought this was a practical solution, but just now i learned there are hooks for some events in obsidian we could use instead like [on('changed')](https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/on('changed')), [on('create')](https://docs.obsidian.md/Reference/TypeScript+API/Vault/on('create')), [on('deleted')](https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/on('deleted')) and [on('rename')](https://docs.obsidian.md/Reference/TypeScript+API/Vault/on('rename')) we could use to optimize this if we'd like to (while the polling works pretty well, but the code is a bit stinky tbh 😅)
- feat: add option to hide habits that do not have activity in shown time frame
	- also made this configurable, since otherwise new habits wouldn't show up at all which i thought would be bad ux.

- I've also taken the liberty to change the readme a bit to simplify the setup process and to explain the new options

This PR is to get feedback and decide what to do with the plugin going forward. Do we want to merge this (or something like it), or should I maintain a fork instead? @zoreet 🤔

### CODE REVIEW

**Comment by zoreet** [comment]
Not sure what to do with this. I don't know svelte and I don't plan on learning it soon, as I'm just starting to learn react.

If we merge then I virtually lock myself out of my own plugin.

If you fork and offer it as a standalone plugin, that is pretty much the same from a user's POV, is I think bad for everyone involved. The users won't know what the difference is, and we will both be working in paralel to build the same thing but share a piece of the traffic.

I hope you'll reconsider going down that route.

**Comment by SarcevicAntonio** [comment]
Hm... that sounds like a catch 22 to me 😅

I guess I could for now just use it for myself, but then it's a shame since I think people could benefit from the additional features, but I'd prefer to contribute here instead of hard forking.

Though, I have to ask: you say you don't know Svelte, but it's a superset of HTML, so you already know more than you think 😁 Have you taken a peak at the code? I could walk you through it, if you are interested. I'd argue Svelte is one of the simpler frameworks to learn, plus the official tutorial is truly amazing! You can learn the basics in like half an hour, so I can only recommend you give it a shot. It would also give you a good basis to then learn to react, since a lot of the concepts apply.

Anyhow, thanks for taking a look and leaving a reply so fast 😁

**Comment by zoreet** [comment]
Ok. I will have a look. I'm AFK this evening, but will check it out tomorrow.

**Comment by zoreet** [comment]
I tried to test this PR but the styles are not loading. I did `npm i && npm run dev`. Is there something else I should do? Something I'm missing?

And then from my repo I symlink main.js and styles.css (which I guess is not needed anymore) to where Obsidian hosts it's files.

**Comment by SarcevicAntonio** [comment]
Strange, doesn't sound like you are missing something... The separate css file shouldn't be needed.

I'm just unsure about the symlink business. I just cloned the repo right inside the obsidian plugin folder and ran the project from there. I need to force reload obsidian to see any changes.

**Pull request closed without merging**
